### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션

### ISSUE THREAD

**Issue by alwn8918** [DS-UMC-7th/UMC-7th-Mati#1]
### 🛠 Mission

개발을 위한 프로젝트 세팅, MVC 패턴과 UIViewController, UIComponents 이해하기

### 📝 To-do

- [x] 1. 프로젝트 파일 생성
- [x] 2. 스토리보드 파일 삭제 및 SceneDelegate 설정
- [x] 3. 폴더 및 파일 생성
- [x] 4. 로그인 레이아웃 구현

### 🔍 접근 방법

추가 예정
