### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by alwn8918** [DS-UMC-7th/UMC-7th-Mati#11]
### 🛠 Mission

객체지향 프로그래밍(OOP)과 SOLID 원칙 이해하기

### 📝 To-do

- [x] 세부화면 레이아웃 구현
- [ ] OOP 원칙을 적용해 리팩토링 진행
- [ ] SOLID 원칙을 적용해 리팩토링 진행

### 🔍 접근 방법

.
