### ISSUE TITLE
[ Week 8 ] 8주차 워크북 미션 

### ISSUE THREAD

**Issue by alwn8918** [DS-UMC-7th/UMC-7th-Mati#14]
### 🛠 Mission

Moya와 Multipart 통신 이해하기

### 📝 To-do

실습
- [x] Moya를 이용해서 유저 정보 받아오기
- [x] 서버에 이미지 업로드 하기

과제
- [x] 검색 화면 및 검색 세부 화면 레이아웃 구현
- [x] 메인 화면과 검색 화면 간 화면 전환 구현
- [x] 주어진 API 명세서를 활용해 검색 세부 화면에서 통신 및 데이터 바인딩 진행

### 🔍 접근 방법

.
