### ISSUE TITLE
[ Week ] 2주차 워크북 미션

### ISSUE THREAD

**Issue by alwn8918** [DS-UMC-7th/UMC-7th-Mati#3]
### 🛠 Mission

AutoLayout과 SnapKit 활용, 화면 전환과 UITabBarController 이해하기

### 📝 To-do

- [ ] TabBarController로 각 화면을 연결
- [ ] 로그인 버튼을 누르면 메인 화면으로 전환 (Modal)
- [ ] 마이페이지 레이아웃 구현
- [ ] 프로필 수정 페이지 레이아웃 구현
- [ ] 프로필 관리 버튼 누르면 프로필 수정 화면으로 전환 (Navigation)
- [ ] 프로필 수정 화면에서 뒤로가기 버튼 누르면 마이페이지 화면으로 전환 (Navigation)

### 🔍 접근 방법

추가 예정
