### ISSUE TITLE
[ Week 3 ] 3주차 워크북 미션

### ISSUE THREAD

**Issue by alwn8918** [DS-UMC-7th/UMC-7th-Mati#5]
### 🛠 Mission

UITableView, 데이터 전달과 UserDefaults 이해하기

### 📝 To-do

- [x] UserDefaults에 데이터 저장 및 출력
- [x] TableView로 주사위 1~6까지 나타내기
- [x] SAVED 탭 Cell, Model 구현
- [x] SAVED 탭 TableView 구현
- [x] LoginView Model 수정
- [x] 마이페이지 뷰 구현
- [x] 프로필 관리 뷰 구현

### 🔍 접근 방법

추가 예정
